name: Deploy OSS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository_owner == 'chaldea-center'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/checkout@v4

      - uses: yizhoumo/setup-ossutil@v2
        if: github.ref == 'refs/heads/main'
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Publish to OSS
        if: github.ref == 'refs/heads/main'
        run: python scripts/publish_oss.py ${{ secrets.OSS_BUCKET_NAME }}
